feat: add prop icon to the FileSelector component
nexxtway/react-rainbow pull request #1811
Opened 2020-09-08 05:35 UTC by rgah2107

fix: #1800

## Changes proposed in this PR:
- add prop icon
- add test for new prop
- add a new InteractiveExample

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

@nexxtway/react-rainbow

2020-09-08 16:10 UTC, LeandroTorresSicilia approved these changes

2020-09-10 16:59 UTC, LeandroTorresSicilia commented on src/components/FileSelector/index.js
> +    icon: PropTypes.node,
let's use uploadIcon instead of icon

2020-09-10 17:15 UTC, TahimiLeonBravo approved these changes

2020-09-10 17:18 UTC, TahimiLeonBravo requested changes

2020-09-10 17:18 UTC, TahimiLeonBravo commented on library/exampleComponents/Icons/picture.js
> +    const { className, style } = props;
Let's the Picture icon from the `@rainbow-modules/icons`

2020-09-11 22:06 UTC, merged