docs: add example with an initial value set in the input component
nexxtway/react-rainbow pull request #1840
Opened 2020-09-21 23:24 UTC by amontalvof

fix: #1831 

## Changes proposed in this PR:
-

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

@nexxtway/react-rainbow

2020-09-24 00:04 UTC, TahimiLeonBravo requested changes

2020-09-24 00:04 UTC, TahimiLeonBravo commented on src/components/Input/readme.md
> +##### input base with an initial value set
I think we should start adding a useful and short little description for the new interactive examples

2020-09-26 15:33 UTC, LeandroTorresSicilia commented on src/components/Input/readme.md
> +    id="input-component-1"
The id must be unique on a web page, the first example already use `id="input-component-1"`
Also keep in mind when adding new examples and use the ids that the integration tests depend on this ids and on the example order too

2020-09-26 16:27 UTC, TahimiLeonBravo approved these changes

2020-09-26 17:27 UTC, TahimiLeonBravo commented
@amontalvof let's do the new examples in this way:
- Each example we should have a title and a description
- It should look like the design https://zpl.io/29LEldY

2020-09-28 05:30 UTC, TahimiLeonBravo commented
@amontalvof we should use a smaller font-size for this example
show as it looks like now
<img width="1326" alt="Screen Shot 2020-09-28 at 12 25 54 AM" src="https://user-images.githubusercontent.com/32083556/94393888-a80e7380-0121-11eb-865c-74519a5df452.png">

2020-09-28 14:17 UTC, merged