refactor: labelAlignment prop on all inputable components
nexxtway/react-rainbow pull request #1869
Opened 2020-09-28 20:26 UTC by rgah2107

fix: #1865

## Changes proposed in this PR:
- add labelAlignment prop to the Label component
- refactor labelAlignment prop on all inputable components
- add labelAlignment prop on all inputable components that don't have it

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

@nexxtway/react-rainbow

2020-09-29 03:34 UTC, yvmunayev approved these changes

2020-10-03 21:10 UTC, TahimiLeonBravo requested changes

2020-10-03 21:23 UTC, TahimiLeonBravo approved these changes

2020-10-04 03:53 UTC, LeandroTorresSicilia commented on src/components/Slider/styled/label.js
>  const StyledLabel = attachThemeAttrs(styled.label)`
why no reuse the input label here?

2020-10-04 03:59 UTC, LeandroTorresSicilia approved these changes

2020-10-04 04:11 UTC, merged