refactor: add new variant 'bare on components using isBare
nexxtway/react-rainbow pull request #1957
Opened 2020-10-28 16:22 UTC by gtallesb

fix: #1934 

## Changes proposed in this PR:
-remove isBare from propTypes and defaultProps on CounterInput.js, Input.js and MultiSelect.js components
-add new variant 'bare on CounterInput.js, Input.js and MultiSelect.js components
-add new variant 'bare on .ts files
-use prop variant
-add new style rule considering variant==='bare' on the styled files for CounterInput.js, Input.js and MultiSelect.js

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

@nexxtway/react-rainbow

2020-10-28 17:53 UTC, TahimiLeonBravo requested changes

2020-10-28 17:53 UTC, TahimiLeonBravo commented on src/components/Input/index.js
>      /** Specifies that an input element should be disabled. This value defaults to false. */
add the `bare` value on the prop variant

2020-10-28 17:55 UTC, TahimiLeonBravo commented
@gtallesb I think you should fix the example https://react-rainbow.io/#!/MultiSelect/5 and use the new `bare` variant instead of the `isBare` prop

2020-10-29 18:33 UTC, gtallesb commented
Got it. Should I add a new example for CounterInput.js component with the bare variant? What about Input component?

2020-11-02 06:26 UTC, merged