feat: add bare variant on the Picklist component
nexxtway/react-rainbow pull request #2065
Opened 2020-12-25 20:21 UTC by rgah2107

fix: #2062

## Changes proposed in this PR:
- add bare variant on the Picklist component
- fix indentation problems in Input component

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

@nexxtway/react-rainbow

2020-12-26 15:39 UTC, LeandroTorresSicilia commented on src/components/Picklist/readme.md
> +                    onChange={handleOnChange}
here we can use ```onChange={setPicklistValue}``` directly

2020-12-26 21:24 UTC, TahimiLeonBravo requested changes

2020-12-26 21:24 UTC, TahimiLeonBravo commented on src/components/Picklist/styled/input.js
> +            box-shadow: ${props.shadows.shadow_10};
when `:hover` add  to the `background-color: `${props.palette.background.main};`

2020-12-27 21:14 UTC, TahimiLeonBravo approved these changes

2020-12-27 21:59 UTC, LeandroTorresSicilia approved these changes

2020-12-27 21:59 UTC, merged