Globalsearch in rainbow components
nexxtway/react-rainbow pull request #2116
Opened 2021-01-21 06:31 UTC by amontalvof

fix: #

## Changes proposed in this PR:
-

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

@nexxtway/react-rainbow

2021-01-21 18:48 UTC, LeandroTorresSicilia commented on library/styleguideComponents/RibbonRenderer/index.js
> -import GlobalSearch from '../GlobalSearch';
if GlobalSearch will not be used more, then go and clean up it and remove all not used

2021-01-23 04:01 UTC, TahimiLeonBravo commented
@amontalvof we need fix this styles 
<img width="1765" alt="Screen Shot 2021-01-22 at 9 56 39 PM" src="https://user-images.githubusercontent.com/32083556/105568222-5e175200-5cfd-11eb-8df5-60c4c9e45730.png">

2021-01-23 04:01 UTC, TahimiLeonBravo requested changes

2021-01-23 04:01 UTC, TahimiLeonBravo commented on library/styleguideComponents/GlobalSearch/algoliaConnectedComponents/AlgoliaLogo/algoliaIcon.js
> -};
I think we should no remove this icon since we are going to use this immediately

2021-01-23 04:01 UTC, TahimiLeonBravo commented on library/styleguideComponents/GlobalSearch/algoliaConnectedComponents/AlgoliaLogo/index.js
> -
I think we should no remove this icon since we are going to use this immediately

2021-01-24 16:34 UTC, LeandroTorresSicilia commented on library/styleguideComponents/UniversalSearch/algoliaIndexes.js
> +export const searchIndexMediums = searchClient.initIndex(indexMediums);
let's invert these names, like componentsSearchIndex

2021-01-24 16:40 UTC, LeandroTorresSicilia commented on library/styleguideComponents/UniversalSearch/PostItemSearchResult.js
> +import React from 'react';
I know we have been inconsistent in the library code, but we can't follow with this inconsistency, I think we should start all files with lower case

2021-01-24 16:42 UTC, LeandroTorresSicilia commented on library/styleguideComponents/UniversalSearch/PostItemSearchResult.js
> +    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
remember, fixed constants that do not depend on function params can be outside, thus avoiding recreating a new object each time

2021-01-24 16:44 UTC, LeandroTorresSicilia commented on library/styleguideComponents/UniversalSearch/PostItemSearchResult.js
> +                    <StyledImage url={image} alt="post" />
since image is an URL and not an image itself we should change its name to imageUrl

2021-01-24 16:45 UTC, LeandroTorresSicilia commented on library/styleguideComponents/UniversalSearch/PostItemSearchResult.js
> +    console.log(image);
remove console

2021-01-25 19:21 UTC, LeandroTorresSicilia approved these changes

2021-01-25 19:22 UTC, merged