fix: fix InternalDropdown search when label is not a string
nexxtway/react-rainbow pull request #2261
Opened 2021-07-16 18:43 UTC by HellWolf93

## Changes proposed in this PR:
- Fix InternalDropdown search when item label is not a string

- [X] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

2021-07-18 12:53 UTC, LeandroTorresSicilia approved these changes

2021-07-21 02:51 UTC, TahimiLeonBravo requested changes

2021-07-21 02:51 UTC, TahimiLeonBravo commented on src/components/Option/index.d.ts
> +    labelText?: string;
let's use "searchableText"

2021-07-21 02:51 UTC, TahimiLeonBravo commented on src/components/PicklistOption/index.d.ts
> +    labelText?: string;
^^

2021-07-21 02:52 UTC, TahimiLeonBravo requested changes

2021-07-21 02:52 UTC, TahimiLeonBravo commented on src/components/PicklistOption/index.js
> +    labelText: PropTypes.string,
^^

2021-07-21 02:52 UTC, TahimiLeonBravo commented on src/components/PicklistOption/index.js
> +    labelText: undefined,
^^

2021-07-21 13:23 UTC, merged