feat: add prop size to chip component
nexxtway/react-rainbow pull request #2581
Opened 2023-01-23 05:51 UTC by yvmunayev

fix: #2535 

## Changes proposed in this PR:
- feat: add prop size to chip component

- [X] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

@nexxtway/react-rainbow

2023-01-24 05:50 UTC, LeandroTorresSicilia approved these changes

2023-01-24 22:49 UTC, TahimiLeonBravo requested changes

2023-01-24 22:49 UTC, TahimiLeonBravo commented on src/components/Chip/styled/container.js
>      ${props =>
We should use different padding when the size is "large" and "small"
large: 1rem
small: 0.5rem

2023-03-10 22:51 UTC, TahimiLeonBravo approved these changes

2023-03-10 22:52 UTC, merged